# Generated by Django 3.0.2 on 2020-01-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='ourMision',
            new_name='ourMission',
        ),
    ]
