# Generated by Django 3.0.2 on 2020-01-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200125_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinformation',
            old_name='adress',
            new_name='address',
        ),
    ]
