# Generated by Django 3.0.2 on 2020-01-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
